services:
  flyway:
    image: flyway/flyway
    command: migrate 
    volumes:
      - ./Flyway/conf:/flyway/conf
      - ./Flyway/sql:/flyway/sql
    depends_on:
      - db
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    volumes: 
      - ./Database/initDB.sql:/docker-entrypoint-initdb.d/initDB.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
  localStack:
    container_name: localStack
    image: localstack/localstack:0.14.5
    ports:
      - 4566:4566
    environment: 
      - SERVICES=sqs
    volumes:
      - ./SQS/create-queue.sh:/docker-entrypoint-initaws.d/create-queue.sh
