services:
  flyway:
    image: flyway/flyway
    command: migrate 
    volumes:
      - ./Flyway/conf:/flyway/conf
      - ./Flyway/sql:/flyway/sql
    depends_on:
      - db
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    volumes: 
      - ./Database/initDB.sql:/docker-entrypoint-initdb.d/initDB.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
#  sqs:
#    container_name: queue-service
#    image: softwaremill/elasticmq-native
#    ports:
#      - 9324:9324
#      - 9325:9325
#    volumes:
#      - ./SQS/custom.conf:/opt/elasticmq.conf
  localStack:
    container_name: localStack
    image: localstack/localstack
    ports:
      - 4566:4566
    environment: 
      - SERVICES=sqs
    volumes:
      - ./SQS/create-queue.sh:/docker-entrypoint-initaws.d/create-queue.sh
